export enum AlertCategory {
  ACCOUNT_ACCESS = 'account-access',
  ACCOUNT_LIST = 'account-list',
  ENTITY_BASIC = 'entity-basic',
  FEE_INFO = 'fee-info',
  USER_INFO = 'user-info',
  SIGNIFICANT_INDIVIDUAL = 'significiant-individual',
  FUTURE_FILING = 'future-filing',
  INVALID_NEXT_AR_YEAR = 'invalid-next-ar-year',
  MISSING_TOKEN = 'missing-token',
  INTERNAL_SERVER_ERROR = 'internal-server-error',
  INVALID_TOKEN = 'invalid-token',
  BUSINESS_DETAILS = 'business-details',
  PAYMENT_ERROR = 'payment-error',
  AR_SUBMIT_ERROR = 'ar-submit-error',
  CREATE_ACCOUNT = 'create-account',
  TOS_GET_ERROR = 'tos-get-error',
  TOS_PATCH_ERROR = 'tos-patch-error',
  FILING_IN_PROGRESS = 'filing-in-progress',
  REQUIRES_STAFF_USER = 'requires-staff-user'
}
